name: Data Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Clean existing databases
        run: rm -f mlflow.db database/dataset.db
      - name: Run Pipeline
        run: python run_pipeline.py
      - name: Run Regression Tests
        run: python scripts/generate_test_queries.py